# Generated by Django 3.0.8 on 2020-07-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_id', models.CharField(max_length=60)),
                ('villian', models.CharField(max_length=60)),
                ('universe', models.CharField(max_length=60)),
            ],
        ),
    ]
